# Generated by Django 5.1.7 on 2025-03-27 16:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recette',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('ingredients', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Etape',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('duree', models.IntegerField()),
                ('type', models.CharField(max_length=50)),
                ('couleur', models.CharField(max_length=20)),
                ('recette', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etapes', to='recettes.recette')),
            ],
        ),
    ]
