# Generated by Django 5.1.7 on 2025-03-27 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recettes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recette',
            name='ingredients',
        ),
        migrations.AddField(
            model_name='recette',
            name='autres_ingredients',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recette',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recette',
            name='quantite_eau',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='recette',
            name='quantite_farine',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='recette',
            name='quantite_levure',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='recette',
            name='quantite_sel',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='recette',
            name='temperature_cuisson',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recette',
            name='temps_cuisson',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
