# Generated by Django 5.1.7 on 2025-03-27 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recettes', '0003_ingredient_recette_ingredients'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recette',
            old_name='temps_cuisson',
            new_name='appret',
        ),
        migrations.RenameField(
            model_name='recette',
            old_name='temperature_cuisson',
            new_name='autolyse',
        ),
        migrations.RemoveField(
            model_name='recette',
            name='autres_ingredients',
        ),
        migrations.RemoveField(
            model_name='recette',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='recette',
            name='quantite_eau',
        ),
        migrations.RemoveField(
            model_name='recette',
            name='quantite_farine',
        ),
        migrations.RemoveField(
            model_name='recette',
            name='quantite_levure',
        ),
        migrations.RemoveField(
            model_name='recette',
            name='quantite_sel',
        ),
        migrations.AddField(
            model_name='recette',
            name='cuisson',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recette',
            name='detente',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recette',
            name='division',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recette',
            name='faconnage',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recette',
            name='petrissage',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recette',
            name='pointage',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recette',
            name='repos_autolyse',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recette',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recette',
            name='nom',
            field=models.CharField(max_length=255),
        ),
        migrations.DeleteModel(
            name='Etape',
        ),
    ]
