# Generated by Django 5.1.7 on 2025-03-27 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recettes', '0004_rename_temps_cuisson_recette_appret_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recette',
            name='ingredients',
        ),
        migrations.AddField(
            model_name='recette',
            name='pointage_froid',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
