# Generated by Django 5.1.7 on 2025-03-27 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recettes', '0005_remove_recette_ingredients_recette_pointage_froid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recette',
            name='pointage_froid',
            field=models.BooleanField(default=False),
        ),
    ]
